# Generated by Django 3.1.5 on 2021-01-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTestResultsIncrease', models.IntegerField(default=0)),
            ],
        ),
    ]
