# Generated by Django 3.1.5 on 2021-01-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='national',
            name='InIcuCumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='InIcuCurrently',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='national',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='deathIncrease',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='hospitalizedCumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='hospitalizedCurrently',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='hospitalizedIncrease',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='negativeIncrease',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='onVentilatorCumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='onVentilatorCurrently',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='positiveIncrease',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='states',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='totalTestResults',
            field=models.IntegerField(default=0),
        ),
    ]
