# Generated by Django 3.1.5 on 2021-01-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210123_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='national',
            name='date',
            field=models.TextField(),
        ),
    ]
