# Generated by Django 3.1.5 on 2021-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210124_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.TextField()),
                ('dataQualityGrade', models.TextField()),
                ('death', models.IntegerField(default=0)),
                ('deathConfirmed', models.IntegerField(default=0)),
                ('deathIncrease', models.IntegerField(default=0)),
                ('deathProbable', models.IntegerField(default=0)),
                ('hospitalized', models.IntegerField(default=0)),
                ('hospitalizedCumulative', models.IntegerField(default=0)),
                ('hospitalizedCurrently', models.IntegerField(default=0)),
                ('hospitalizedIncrease', models.IntegerField(default=0)),
                ('inIcuCumulative', models.IntegerField(default=0)),
                ('inIcuCurrently', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('negativeIncrease', models.IntegerField(default=0)),
                ('negativeTestsAntibody', models.IntegerField(default=0)),
                ('negativeTestsPeopleAntibody', models.IntegerField(default=0)),
                ('negativeTestsViral', models.IntegerField(default=0)),
                ('onVentilatorCumulative', models.IntegerField(default=0)),
                ('onVentilatorCurrently', models.IntegerField(default=0)),
                ('positive', models.IntegerField(default=0)),
                ('positiveCasesViral', models.IntegerField(default=0)),
                ('positiveIncrease', models.IntegerField(default=0)),
                ('positiveScore', models.IntegerField(default=0)),
                ('positiveTestsAntibody', models.IntegerField(default=0)),
                ('positiveTestsAntigen', models.IntegerField(default=0)),
                ('positiveTestsPeopleAntibody', models.IntegerField(default=0)),
                ('positiveTestsPeopleAntigen', models.IntegerField(default=0)),
                ('positiveTestsViral', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('totalTestEncountersViral', models.IntegerField(default=0)),
                ('totalTestEncountersViralIncrease', models.IntegerField(default=0)),
                ('totalTestResults', models.IntegerField(default=0)),
                ('totalTestResultsIncrease', models.IntegerField(default=0)),
                ('totalTestsAntibody', models.IntegerField(default=0)),
                ('totalTestsAntigen', models.IntegerField(default=0)),
                ('totalTestsPeopleAntibody', models.IntegerField(default=0)),
                ('totalTestsPeopleAntigen', models.IntegerField(default=0)),
                ('totalTestsPeopleViral', models.IntegerField(default=0)),
                ('totalTestsPeopleViralIncrease', models.IntegerField(default=0)),
                ('totalTestsVira', models.IntegerField(default=0)),
                ('totalTestsViralIncrease', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='national',
            name='date',
            field=models.DateField(),
        ),
    ]
