# Generated by Django 3.1.5 on 2021-01-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210124_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='totalTestsVira',
            new_name='totalTestsViral',
        ),
    ]
