# Generated by Django 3.1.5 on 2021-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210125_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='national',
            name='date',
            field=models.DateField(),
        ),
    ]
