# Generated by Django 3.1.5 on 2021-01-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210126_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='national',
            name='InIcuCumulative',
        ),
        migrations.RemoveField(
            model_name='national',
            name='InIcuCurrently',
        ),
        migrations.AddField(
            model_name='national',
            name='inIcuCumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='national',
            name='inIcuCurrently',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='national',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='national',
            name='hospitalizedCumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='national',
            name='hospitalizedCurrently',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='national',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='national',
            name='onVentilatorCumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='national',
            name='onVentilatorCurrently',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='national',
            name='positive',
            field=models.IntegerField(default=0),
        ),
    ]
