# Generated by Django 3.1.5 on 2021-01-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210127_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='national',
            name='deathIncrease',
            field=models.IntegerField(default=0),
        ),
    ]
