# Generated by Django 3.1.5 on 2021-01-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_national_deathincrease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='national',
            name='date',
            field=models.DateField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
    ]
