# Generated by Django 3.1.5 on 2021-01-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210129_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='totalTestsVira',
            new_name='totalTestsViral',
        ),
    ]
