# Generated by Django 3.1.5 on 2021-01-29 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210129_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='national',
            old_name='inIcuCumulative',
            new_name='InIcuCumulative',
        ),
        migrations.RenameField(
            model_name='national',
            old_name='inIcuCurrently',
            new_name='InIcuCurrently',
        ),
    ]
